title: Akshay Shinde # your name (or website title) here
logo: "/images/logo1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  shindeakshay285@gmail.com 
  <br><br>
  +91 8308704375
  <br><br>
  <a href="https://www.linkedin.com/in/akshay-shinde-410bb5101">View My LinkedIn Profile</a> 
  <a href="https://github.com/akshayshidee">View My Github Profile</a> 
  
theme: jekyll-theme-minimal
